name: Bug report
description: Report bugs or glitches to us
title: '[Bug]: '
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Conditions
      options:
        - label: I use the latest version
          required: false
        - label: I use a vanilla version of the program
          required: false
        - label: I have read the documentation
          required: true
  - type: dropdown
    attributes:
      label: Version type
      description: Choose between release or dev build
      options:
        - release
        - dev build
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Full version
      placeholder: ex. release-1.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception or Error
      description: provide error logs





