
name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r src/requirements.txt

    - name: build with pyinstaller
      run: |
        ./src/build.bat

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/main.exe
